# Generated by Django 3.1.2 on 2021-03-26 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20210326_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrator',
            name='profile_pic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.profile'),
        ),
        migrations.AddField(
            model_name='contact',
            name='profile_pic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.profile'),
        ),
    ]
