# Generated by Django 3.1.2 on 2021-03-31 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_auto_20210326_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=models.ImageField(upload_to='logo/'),
        ),
    ]
