# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- backlog_item_880

pool:
  vmImage: ubuntu-latest

variables:
  pythonVersion: 3.7

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(pythonVersion)'
  displayName: 'Use Python $(pythonVersion)'

- script: |
      virtualenv antenv
      source antenv/bin/activate
      python -m pip install --upgrade pip
      pip install setup
      pip install -r requirements.txt
  workingDirectory: $(Build.SourcesDirectory)/backend
  displayName: "Install requirements"

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)/backend'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/Application$(Build.BuildId).zip'
    replaceExistingArchive: true
    verbose: true
    
- publish: $(Build.ArtifactStagingDirectory)/Application$(Build.BuildId).zip
  displayName: 'Upload package'
  artifact: drop
  
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'PushInsightsDevPAYG'
    appType: 'webAppLinux'
    WebAppName: 'pinsight'
    packageForLinux: $(Build.ArtifactStagingDirectory)/Application$(Build.BuildId).zip
    RuntimeStack: 'PYTHON|3.7'