# Generated by Django 3.1.6 on 2021-04-19 12:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210416_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderbook',
            name='duration',
            field=models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='orderbook',
            name='return_date',
            field=models.DateTimeField(),
        ),
    ]
