# Generated by Django 3.1.6 on 2021-04-19 13:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210419_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderbook',
            name='return_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 22, 13, 3, 31, 341478)),
        ),
    ]
