# Generated by Django 3.1.12 on 2021-06-18 14:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210423_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderbook',
            name='return_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 21, 14, 3, 36, 838849)),
        ),
    ]
