# Generated by Django 3.1.12 on 2021-06-18 14:21

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210618_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='copies',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2000)]),
        ),
        migrations.AlterField(
            model_name='orderbook',
            name='return_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 21, 14, 21, 10, 149394)),
        ),
    ]
