# Generated by Django 3.1.12 on 2021-06-18 14:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210618_1421'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='book',
        #     name='number_of_books',
        # ),
        migrations.AlterField(
            model_name='orderbook',
            name='return_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 21, 14, 25, 41, 123495)),
        ),
    ]
