# Generated by Django 3.1.12 on 2021-06-18 14:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210618_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderbook',
            name='return_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 21, 14, 27, 17, 270773)),
        ),
    ]
