# Generated by Django 3.1.6 on 2021-06-28 17:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20210618_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderbook',
            name='return_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 1, 17, 19, 29, 460354)),
        ),
    ]
