# Generated by Django 3.1.6 on 2021-07-06 13:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20210628_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowbook',
            name='return_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 9, 13, 48, 58, 348765)),
        ),
    ]
