# Generated by Django 3.1.12 on 2021-07-07 18:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20210706_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowbook',
            name='return_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 10, 18, 6, 16, 174760)),
        ),
        migrations.AlterUniqueTogether(
            name='borrowbook',
            unique_together={('book', 'borrowed_by')},
        ),
    ]
