# Generated by Django 3.1.2 on 2021-02-26 17:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projectapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectmember',
            old_name='user',
            new_name='invitee_id',
        ),
        migrations.AlterUniqueTogether(
            name='projectmember',
            unique_together={('invitee_id', 'project')},
        ),
    ]
