# Generated by Django 3.1.2 on 2021-03-03 09:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projectapp', '0002_auto_20210226_1705'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectmember',
            old_name='invitee_id',
            new_name='user_id',
        ),
        migrations.AlterUniqueTogether(
            name='projectmember',
            unique_together={('user_id', 'project')},
        ),
    ]
