# Generated by Django 3.1.2 on 2021-03-03 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0003_auto_20210303_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmember',
            name='approval_status',
            field=models.CharField(choices=[('0', 'Pending Approval'), ('1', 'Approved'), ('2', 'Rejected')], default='0', max_length=2),
        ),
    ]
