# Generated by Django 3.1.2 on 2021-03-11 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0004_projectmember_approval_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='created_at',
            new_name='published_at',
        ),
        migrations.RenameField(
            model_name='projectmember',
            old_name='created_at',
            new_name='published_at',
        ),
        migrations.RenameField(
            model_name='projectmember',
            old_name='project_member_role',
            new_name='role',
        ),
        migrations.RenameField(
            model_name='projectmember',
            old_name='user_id',
            new_name='user',
        ),
    ]
