# Generated by Django 3.1.2 on 2021-03-12 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0005_auto_20210311_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmemberrole',
            name='name',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Member', 'Member')], default='Member', max_length=13),
        ),
    ]
