# Generated by Django 3.1.7 on 2021-03-25 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('books', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='books', to='app.book')),
            ],
        ),
    ]
