# Generated by Django 3.1.2 on 2021-03-29 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_book_book_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='number_of_books',
            field=models.IntegerField(default=0),
        ),
    ]
