# Generated by Django 3.1.2 on 2021-03-29 20:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_orderbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderbook',
            name='date_borrowed',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='orderbook',
            name='return_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
