# Generated by Django 3.1.2 on 2021-03-09 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0004_projectmember_approval_status'),
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveydetails',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='survey_project', to='projectapp.project'),
        ),
    ]
