# Generated by Django 3.1.2 on 2021-03-11 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_auto_20210309_1502'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surveydetails',
            old_name='project_id',
            new_name='project',
        ),
    ]
