# Generated by Django 3.1.2 on 2021-03-11 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('surveys', '0003_auto_20210311_1427'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surveydetails',
            old_name='created_at',
            new_name='published_at',
        ),
        migrations.CreateModel(
            name='SurveyProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('questions_completed', models.IntegerField()),
                ('is_completed', models.BooleanField(default=False)),
                ('last_modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_current', models.BooleanField(default=False)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='surveys.surveydetails')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
