# Generated by Django 3.1.2 on 2021-03-03 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projectapp', '0004_projectmember_approval_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Report Name')),
                ('description', models.TextField(verbose_name='Report Description')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('last_updated_at', models.DateField(auto_now_add=True)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projectapp.project')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
