# Generated by Django 3.1.2 on 2021-03-03 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False)),
                ('report_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='report.report')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
