# Generated by Django 3.1.2 on 2021-03-05 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0004_projectmember_approval_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('report', '0002_reportversion'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='report',
            unique_together={('project_id', 'name')},
        ),
        migrations.CreateModel(
            name='ReportMemberVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('report_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='report.reportversion')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
