# Generated by Django 3.1.2 on 2021-03-11 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0005_auto_20210311_1642'),
        ('report', '0005_auto_20210309_1654'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='created_at',
            new_name='last_modified',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='project_id',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='last_updated_at',
            new_name='published_at',
        ),
        migrations.RenameField(
            model_name='reportmemberversion',
            old_name='member_id',
            new_name='member',
        ),
        migrations.RenameField(
            model_name='reportversion',
            old_name='updated_at',
            new_name='last_modified',
        ),
        migrations.RenameField(
            model_name='reportversion',
            old_name='report_id',
            new_name='report',
        ),
        migrations.AlterUniqueTogether(
            name='report',
            unique_together={('project', 'name')},
        ),
    ]
