# Generated by Django 3.1.2 on 2021-02-01 14:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210201_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2021, 2, 1, 14, 7, 50, 357397, tzinfo=utc)),
        ),
    ]
