# Generated by Django 3.1.2 on 2021-02-01 14:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210201_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2021, 2, 1, 14, 44, 37, 183789, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='othernames',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Other names'),
        ),
    ]
