# Generated by Django 3.1.2 on 2021-02-10 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210201_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmember',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
