# Generated by Django 3.1.2 on 2021-02-10 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20210210_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmember',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
