# Generated by Django 3.1.2 on 2021-02-11 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20210210_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmemberrole',
            name='name',
            field=models.CharField(choices=[('admin', 'Administrator'), ('member', 'Member')], default='member', max_length=13),
        ),
    ]
