# Generated by Django 3.1.2 on 2021-02-11 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20210211_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmemberrole',
            name='description',
        ),
        migrations.AlterField(
            model_name='projectmember',
            name='project_member_role',
            field=models.ForeignKey(default='member', on_delete=django.db.models.deletion.PROTECT, related_name='project_member_role', to='app.projectmemberrole'),
        ),
    ]
