# Generated by Django 3.1.2 on 2021-02-15 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20210211_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmember',
            name='project_member_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_member_role', to='app.projectmemberrole'),
        ),
    ]
