# Generated by Django 3.1.2 on 2021-02-15 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20210215_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmemberrole',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='projectmemberrole',
            name='is_member',
        ),
    ]
