# Generated by Django 3.1.2 on 2021-02-15 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20210215_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmemberrole',
            name='name',
            field=models.CharField(choices=[('Administrator', 'Administrator'), ('Member', 'Member')], default='Member', max_length=13),
        ),
    ]
