# Generated by Django 3.1.2 on 2021-02-26 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20210215_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='company',
        ),
        migrations.RemoveField(
            model_name='project',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='projectdashboard',
            name='project',
        ),
        migrations.AlterUniqueTogether(
            name='projectmember',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='projectmember',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projectmember',
            name='project_member_role',
        ),
        migrations.RemoveField(
            model_name='projectmember',
            name='user',
        ),
    ]
