# Generated by Django 3.1.2 on 2021-03-11 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20210226_1450'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='created_at',
            new_name='published_at',
        ),
    ]
