# Generated by Django 3.1.2 on 2021-06-03 20:01

import app.file_validator
import app.models.custom_azure
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20210311_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='data_file',
            field=models.FileField(blank=True, null=True, storage=app.models.custom_azure.PublicMediaAzureStorage, upload_to='File', validators=[app.file_validator.validate_file]),
        ),
    ]
