# Generated by Django 3.1.2 on 2021-06-04 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20210603_2025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileupload',
            old_name='tittle',
            new_name='title',
        ),
    ]
