# Generated by Django 3.1.2 on 2021-06-09 19:20

import app.file_validator
import app.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20210604_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='data_file',
            field=models.FileField(blank=True, null=True, upload_to=app.utils.Utils.create_path, validators=[
                                   app.file_validator.validate_file]),
        ),
        migrations.CreateModel(
            name='CompanyFileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('data_file', models.FileField(blank=True, null=True,
                                               upload_to=app.utils.Utils.create_path, validators=[app.file_validator.validate_file])),
                ('comment', models.CharField(max_length=400, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                              related_name='file_company_company', to='app.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                           related_name='company_file_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
