# Generated by Django 3.1.2 on 2021-06-09 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20210609_1920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyfileupload',
            name='company',
        ),
    ]
