# Generated by Django 3.1.2 on 2021-06-28 12:40

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_auto_20210621_1159'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompaniesWhitelist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('domain_names', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), size=None)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.company')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
