# Generated by Django 3.1.2 on 2021-07-01 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_companieswhitelist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyfileupload',
            name='title',
        ),
    ]
