# Generated by Django 3.1.2 on 2021-07-01 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_remove_companyfileupload_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyfileupload',
            name='title',
            field=models.CharField(default='A new title', max_length=100),
        ),
    ]
