# Generated by Django 3.1.2 on 2021-07-08 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_remove_companyfileupload_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyfileupload',
            name='name',
            field=models.CharField(blank=True, default='file name', max_length=100, null=True),
        ),
    ]
