# Generated by Django 3.1.2 on 2021-08-10 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_auto_20210715_2128'),
    ]

    operations = [
        migrations.CreateModel(
            name='AzureDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('azure_account_name', models.CharField(max_length=128, null=True)),
                ('azure_account_key', models.CharField(max_length=350)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='company',
            name='azure_details',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.azuredetails'),
        ),
    ]
